project:
  type: website
  output-dir: _site
  render:
    - home.qmd
    - "trackers/*.qmd"
    - "!old/**"
  resources:
    - "assets/**"

website:
  title: "euverse"
  site-url: "https://michalovadek.github.io/euverse"
  open-graph: true
  navbar:
    left:
      - href: home.qmd
        text: Home
      - text: Trackers
        menu:
          - href: trackers/eu-finance.qmd
            text: EU Finance
          - href: trackers/eu-vetoes.qmd
            text: EU Vetoes
          - href: trackers/eu-court.qmd
            text: EU Court
          - href: trackers/eu-law.qmd
            text: EU Law

format:
  html:
    theme:
      light: [zephyr, assets/style.scss]
      dark:  [darkly, assets/style.scss]
    include-in-header: assets/header.html
    toc: false
    smooth-scroll: true

execute:
  freeze: auto
